### ISSUE TITLE
FG_KASLR bypass

### ISSUE THREAD

**Issue by HacKurx** [kaccardi/linux#27]
Hi,

After reading [this article](https://blog.blazeinfosec.com/the-never-ending-problems-of-local-aslr-holes-in-linux/), I just tested on FG_KASLR the [PoC aslrekt](https://github.com/blazeinfosec/aslrekt) (from @blazeinfosec).
Here is the return:
```
hackurx@debian:~/Bureau$ grep ASLR /boot/config-5.5.0-rc7 
CONFIG_FG_KASLR=y
hackurx@debian:~/Bureau$ ./aslrekt 
***** ASLREKT *****
Mot de passe : 
[+] /bin/su .text is at 0x562f5e5d2000
[+] /bin/su heap is at 0x562f5f125000
[+] /bin/su stack is at 0x7fffcaf33000 
```

Given your work in progress, do you think you can correct this kind of problem?

Thanks.

Best regards,

**Comment by HacKurx** [comment]
To inspire yourself with a good solution:
https://github.com/HacKurx/linux-grsecurity/commit/b718173f014ed16f3e61066300431662af765bc9#diff-407c73155551d6f8af7c86b9c805569c

**Comment by kaccardi** [comment]
Hi! Thanks so much for your question! I appreciate the pointer to the
blog post.

On Tue, 2020-02-11 at 09:55 -0800, Loïc wrote:
> Hi,
> After reading this article, I just tested on FG_KASLR the PoC aslrekt
> (from @blazeinfosec).
> Here is the return:
> hackurx@debian:~/Bureau$ grep ASLR /boot/config-5.5.0-rc7 
> CONFIG_FG_KASLR=y
> hackurx@debian:~/Bureau$ ./aslrekt 
> ***** ASLREKT *****
> Mot de passe : 
> [+] /bin/su .text is at 0x562f5e5d2000
> [+] /bin/su heap is at 0x562f5f125000
> [+] /bin/su stack is at 0x7fffcaf33000 
> Given your work in progress, do you think you can correct this kind
> of problem?
> Thanks.
> Best regards,
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.

It is possible I'm misunderstanding your question, but this article is
referencing an exploit on user space ASLR, right? My patchset is only
designed to help with kernel ASLR, and I did not implement any code to
do anything to userspace ASLR. I agree with the premise though - there
are many and varied infoleaks and ASLR (kernel or otherwise) isn't good
enough in and of itself. It is also still true (as referenced in the
article) that aslr is really useful when your threat model doesn't
include local access. So, to answer your question, no - my patch will
not address attacks on user space ASLR, so issues will continue to
exist.
